name: Add one day per day
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    
jobs:
  add_one:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2.3.3
    - run: echo -n -e "HELLO\n !\n World!"
    - run: cat README.md
      
